services:
  zotero-genetics-daily:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/zotero-genetics-daily:latest
    container_name: zotero-genetics-daily
    network_mode: bridge
    restart: unless-stopped

    environment:
      # Required parameters (example values)
      - ZOTERO_ID=1234567
      - ZOTERO_KEY=AbCdEfGhIjKlMnOpQrStUvWx
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=465
      - SENDER=your_email@example.com
      - SENDER_PASSWORD=your_email_password
      - RECEIVER=receiver_email@example.com

      # Optional parameters (have defaults in main.py)
      - ZOTERO_IGNORE=already_read_papers
      - SEND_EMPTY=False
      - MAX_PAPER_NUM=5
      - USE_LLM_API=1
      - OPENAI_API_KEY=sk-your-openai-key-here
      - OPENAI_API_BASE=https://api.openai.com/v1
      - MODEL_NAME=Qwen/Qwen1.5-7B-Instruct
      - LANGUAGE=English

      # New: semicolon-separated favourite authors
      - FAVORITE_AUTHORS=Yamanaka S.;Li W.;Smith J. R.;Brown

      # New configuration for Hugging Face mirror
      - HF_ENDPOINT=https://hf-mirror.com
      # - TZ=Asia/Shanghai
      # - http_proxy=http://proxy.example.com:8080
      # - https_proxy=http://proxy.example.com:8080
      # - no_proxy=localhost,127.0.0.1,.internal

    volumes:
      - ./logs:/var/log/cron
      # - ./models:/app/models
      - /etc/localtime:/etc/localtime:ro

    command: >
      bash -c "
      rm -f /var/run/crond.pid /var/run/cron.pid &&
      printenv | grep -v 'no_proxy' >> /etc/environment &&
      echo '0 8 * * * root cd /app && /usr/local/bin/uv run main.py >> /var/log/cron/cron.log 2>&1' > /etc/cron.d/zotero-job &&
      chmod 0644 /etc/cron.d/zotero-job &&
      touch /var/log/cron/cron.log &&
      cron -f &
      tail -f /var/log/cron/cron.log
      "
