name: Send emails daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest

    steps:
      # ---------------- checkout repo ---------------- #
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref:        ${{ vars.REF }}

      # ---------------- install uv ------------------- #
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      # ---------------- run script ------------------- #
      - name: Run script
        env:
          # -------- Zotero --------
          ZOTERO_ID:      ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY:     ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE:  ${{ vars.ZOTERO_IGNORE }}

          # -------- delivery behaviour --------
          SEND_EMPTY:     ${{ vars.SEND_EMPTY }}
          MAX_PAPER_NUM:  ${{ vars.MAX_PAPER_NUM }}

          # -------- e-mail --------
          SMTP_SERVER:     ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:       ${{ secrets.SMTP_PORT }}
          SENDER:          ${{ secrets.SENDER }}
          RECEIVER:        ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}

          # -------- LLM --------
          USE_LLM_API:     ${{ secrets.USE_LLM_API }}
          #OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }} 
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME:      ${{ secrets.MODEL_NAME }}
          LANGUAGE:        ${{ vars.LANGUAGE }}
          # 新增密钥池参数
          LLM_KEY_POOL_BLACKLIST_THRESHOLD: ${{ vars.LLM_KEY_POOL_BLACKLIST_THRESHOLD }}
          LLM_KEY_POOL_RECOVERY_INTERVAL:   ${{ vars.LLM_KEY_POOL_RECOVERY_INTERVAL }}
          LLM_KEY_POOL_RPM_LIMIT:           ${{ secrets.LLM_KEY_POOL_RPM_LIMIT }}
          CONCURRENCY_LIMIT:                  ${{ vars.CONCURRENCY_LIMIT }}
          # -------- favorite authors --------
          FAVORITE_AUTHORS: ${{ secrets.FAVORITE_AUTHORS }}
        run: |
          uv run main.py
